---
- hosts: all
  become: true
  sudo: yes
  tasks:
    - name: Task 1 - cd to correct DIR
      command: cd /opt/observium

    - name: Task 2 - Create a directory
      command: svn cleanup

    - name: Task 3 - Start a service
      command: svn update
