---
- hosts: all
  become: true
  become_user: lee.kendrick
  tasks:
    - name: Task 1 - cd to correct DIR
      command: cd /opt/observium

    - name: Task 2 - Create a directory
      command: sudo svn cleanup

    - name: Task 3 - Start a service
      command: sudo svn update
